#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lazy
Version  : 1.4
Release  : 1
URL      : https://files.pythonhosted.org/packages/ce/10/2c0cd8a601fff792f814b89233859e3fce2e266a5defd8af3bcadbe5c7ef/lazy-1.4.zip
Source0  : https://files.pythonhosted.org/packages/ce/10/2c0cd8a601fff792f814b89233859e3fce2e266a5defd8af3bcadbe5c7ef/lazy-1.4.zip
Summary  : Lazy attributes for Python objects
Group    : Development/Tools
License  : BSD-2-Clause
Requires: lazy-python = %{version}-%{release}
Requires: lazy-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
====
lazy
====
----------------------------------
Lazy attributes for Python objects
----------------------------------

%package python
Summary: python components for the lazy package.
Group: Default
Requires: lazy-python3 = %{version}-%{release}

%description python
python components for the lazy package.


%package python3
Summary: python3 components for the lazy package.
Group: Default
Requires: python3-core

%description python3
python3 components for the lazy package.


%prep
%setup -q -n lazy-1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550504263
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
